export enum AuditModule {
  REQUEST = 'REQUEST',
  APPROVAL_STEP = 'APPROVAL_STEP',
  DELEGATION = 'DELEGATION',
  USER = 'USER',
  LEAVE_BALANCE = 'LEAVE_BALANCE',
  FORM_TEMPLATE = 'FORM_TEMPLATE',
  ROLE = 'ROLE',
  DEPARTMENT = 'DEPARTMENT',
  POSITION = 'POSITION',
  SYSTEM_SETTING = 'SYSTEM_SETTING',
  AUTH = 'AUTH',
  NOTIFICATION = 'NOTIFICATION',
  UNKNOWN = 'UNKNOWN',
}

export const AUDIT_MODULE_ARRAY = Object.values(AuditModule);
