export enum NotificationType {
  REQUEST_ASSIGNED = 'REQUEST_ASSIGNED',
  REQUEST_REMINDER = 'REQUEST_REMINDER',
  DELEGATION_RECEIVED = 'DELEGATION_RECEIVED',
  REQUEST_APPROVED = 'REQUEST_APPROVED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
  REQUEST_RETURNED = 'REQUEST_RETURNED',
  STEP_APPROVED = 'STEP_APPROVED',
  DELEGATION_EXPIRED = 'DELEGATION_EXPIRED',
  LEAVE_BALANCE_UPDATED = 'LEAVE_BALANCE_UPDATED',
}

export const NOTIFICATION_TYPE_ARRAY = Object.values(NotificationType);
