const annualLeaveFields = [
  {
    id: 'container_6gnf7oba',
    type: 'container',
    label: 'New container',
    placeholder: '',
    required: false,
    readOnly: false,
    order: 0,
    parentId: null,
    layout: {
      direction: 'row',
    },
  },
  {
    id: 'reason',
    type: 'textarea',
    label: 'Reason',
    placeholder: 'Enter reason',
    required: false,
    readOnly: false,
    order: 1,
    parentId: null,
    layout: {
      direction: 'col',
    },
  },
  {
    id: 'startDate',
    type: 'date',
    label: 'Start Date',
    placeholder: 'Enter start date',
    required: true,
    readOnly: false,
    order: 2,
    parentId: 'container_6gnf7oba',
    layout: {
      direction: 'col',
    },
  },
  {
    id: 'endDate',
    type: 'date',
    label: 'End Date',
    placeholder: 'Enter end date',
    required: true,
    readOnly: false,
    order: 3,
    parentId: 'container_6gnf7oba',
    layout: {
      direction: 'col',
    },
  },
];

export const formTemplateSeed = [
  {
    code: 'ANNUAL_LEAVE',
    vieName: 'Đơn Xin Nghỉ Phép Năm',
    engName: 'Annual Leave Request',
    fields: annualLeaveFields,
    version: 1,
    isActive: true,
    submitButtonText: 'Gửi yêu cầu',
    autoApprove: false,
    maxDays: 12,
    requireAttachment: false,
    isReductible: true,
  },
  {
    code: 'RESIGNATION_LEAVE',
    vieName: 'Đơn Nghỉ Việc',
    engName: 'Resignation Request',
    fields: annualLeaveFields,
    version: 1,
    isActive: true,
    submitButtonText: 'Gửi yêu cầu',
    autoApprove: false,
    maxDays: 12,
    requireAttachment: false,
    isReductible: true,
  },
  {
    code: 'UNPAID_LEAVE',
    vieName: 'Đơn Nghỉ Không Lương',
    engName: 'Unpaid Leave Request',
    fields: annualLeaveFields,
    version: 1,
    isActive: true,
    submitButtonText: 'Gửi yêu cầu',
    autoApprove: false,
    maxDays: 12,
    requireAttachment: false,
    isReductible: true,
  },
];
