const annualLeaveFields = [
  {
    id: 'container_7cd2waef',
    type: 'container',
    label: 'New container',
    name: 'container_4w0o2x2i',
    placeholder: '',
    note: '',
    required: false,
    readOnly: false,
    order: 0,
    parentId: null,
    layout: {
      direction: 'row',
    },
  },
  {
    id: 'textarea_bef35fy8',
    type: 'textarea',
    label: 'Lý do xin nghỉ',
    name: 'reason',
    placeholder: 'Nhập lý do xin nghỉ',
    note: '',
    required: false,
    readOnly: false,
    order: 1,
    parentId: null,
  },
  {
    id: 'date_2hxuaq1n',
    type: 'date',
    label: 'Ngày bắt đầu nghỉ',
    name: 'startDate',
    placeholder: 'Nhập ngày bắt đầu nghỉ',
    note: '',
    required: true,
    readOnly: false,
    order: 2,
    parentId: 'container_7cd2waef',
  },
  {
    id: 'date_47j8zyot',
    type: 'date',
    label: 'Ngày kết thúc nghỉ',
    name: 'endDate',
    placeholder: 'Nhập ngày kết thúc nghỉ',
    note: '',
    required: true,
    readOnly: false,
    order: 3,
    parentId: 'container_7cd2waef',
  },
];

const resignationFields = [
  {
    id: 'date_541imm8d',
    type: 'date',
    label: 'Ngày làm việc cuối cùng',
    name: 'endDate',
    placeholder: 'Nhập ngày kết thúc nghỉ',
    note: '',
    required: true,
    readOnly: false,
    order: 0,
    parentId: null,
  },
  {
    id: 'confirm_lgihlgky',
    type: 'confirm',
    label: 'Xác nhận sử dụng hết phép năm còn lại',
    name: 'confirm_83p7y1ch',
    placeholder: '',
    note: '',
    required: true,
    readOnly: false,
    order: 1,
    parentId: null,
  },
  {
    id: 'container_9nqnbv28',
    type: 'container',
    label: 'New container',
    name: 'container_9gv8mj1m',
    placeholder: '',
    note: '',
    required: false,
    readOnly: false,
    order: 2,
    parentId: null,
    layout: {
      direction: 'row',
    },
  },
  {
    id: 'file_h02amx0z',
    type: 'file',
    label: 'New file',
    name: 'file_p3zclua5',
    placeholder: '',
    note: '',
    required: false,
    readOnly: false,
    order: 3,
    parentId: null,
  },
  {
    id: 'text_41mr90d1',
    type: 'text',
    label: 'Người nhận bàn giao',
    name: 'text_8g5u9z82',
    placeholder: '',
    note: '',
    required: false,
    readOnly: false,
    order: 4,
    parentId: null,
  },
  {
    id: 'textarea_ub8deqe0',
    type: 'textarea',
    label: 'Các công việc tồn đọng',
    name: 'textarea_ejhe1ajr',
    placeholder: 'Vui lòng điền các công việc tồn đọng',
    note: '',
    required: false,
    readOnly: false,
    order: 5,
    parentId: null,
  },
  {
    id: 'confirm_twec4iqw',
    type: 'confirm',
    label:
      'Tôi cam kết hoàn thành việc bàn giao tài liệu và tài sản công ty trước ngày nghỉ việc',
    name: 'confirm_3n6ikunt',
    placeholder: '',
    note: '',
    required: true,
    readOnly: false,
    order: 6,
    parentId: null,
  },
  {
    id: 'signature_p4k08him',
    type: 'signature',
    label: 'Ký ở đây',
    name: 'signature_vn1y3byg',
    placeholder: '',
    note: '',
    required: false,
    readOnly: false,
    order: 7,
    parentId: null,
  },
  {
    id: 'select_a0v92x0a',
    type: 'select',
    label: 'Phân loại lí do',
    name: 'select_9fuby2p2',
    placeholder: 'Vui lòng chọn phân loại lí do',
    note: '',
    required: true,
    readOnly: false,
    options: [
      {
        label: 'Cơ hội nghề nghiệp mới',
        value: 'opt_1',
      },
      {
        label: 'Lý do  gia đình',
        value: 'opt_1775619185382',
      },
      {
        label: 'Đi học',
        value: 'opt_1775619185522',
      },
      {
        label: 'Thay đổi môi trường',
        value: 'opt_1775619252660',
      },
      {
        label: 'Khác',
        value: 'opt_1775619258101',
      },
    ],
    order: 8,
    parentId: 'container_9nqnbv28',
  },
  {
    id: 'textarea_rjwigx2b',
    type: 'textarea',
    label: 'Lý do chi tiết',
    name: 'reason',
    placeholder: 'Nhập lý do xin nghỉ',
    note: '',
    required: true,
    readOnly: false,
    order: 9,
    parentId: 'container_9nqnbv28',
  },
];
const unpaidLeaveFields = [
  {
    id: 'container_4oe8opg9',
    type: 'container',
    label: 'New container',
    name: 'container_o89rwrvx',
    placeholder: '',
    note: '',
    required: false,
    readOnly: false,
    order: 0,
    parentId: null,
    layout: {
      direction: 'row',
    },
  },
  {
    id: 'date_quqpwl1n',
    type: 'date',
    label: 'Ngày bắt đầu nghỉ',
    name: 'startDate',
    placeholder: 'Nhập ngày bắt đầu nghỉ',
    note: '',
    required: false,
    readOnly: false,
    order: 1,
    parentId: 'container_4oe8opg9',
  },
  {
    id: 'date_rrstlcbh',
    type: 'date',
    label: 'Ngày kết thúc nghỉ',
    name: 'endDate',
    placeholder: 'Nhập ngày kết thúc nghỉ',
    note: '',
    required: false,
    readOnly: false,
    order: 2,
    parentId: 'container_4oe8opg9',
  },
  {
    id: 'container_09a5ow5r',
    type: 'container',
    label: 'New container',
    name: 'container_4i28hrdg',
    placeholder: '',
    note: '',
    required: false,
    readOnly: false,
    order: 3,
    parentId: null,
    layout: {
      direction: 'row',
    },
  },
  {
    id: 'select_28meh3d4',
    type: 'select',
    label: 'Lý do xin nghỉ',
    name: 'reasonCategory',
    placeholder: 'Select Lý do xin nghỉ',
    note: '',
    required: true,
    readOnly: false,
    options: [
      {
        label: 'Ốm đau',
        value: 'sick',
      },
      {
        label: 'Việc riêng',
        value: 'personal',
      },
      {
        label: 'Khác',
        value: 'other',
      },
    ],
    order: 4,
    parentId: 'container_09a5ow5r',
  },
  {
    id: 'textarea_gf0lo3wz',
    type: 'textarea',
    label: 'Chi tiết lý do',
    name: 'detailReason',
    placeholder: 'Nhập chi tiết lý do',
    note: '',
    required: false,
    readOnly: false,
    order: 5,
    parentId: 'container_09a5ow5r',
  },
  {
    id: 'textarea_54x4huf9',
    type: 'textarea',
    label: 'Thông tin bàn giao',
    name: 'handoverDetail',
    placeholder: 'Nhập thông tin bàn giao',
    note: '',
    required: false,
    readOnly: false,
    order: 6,
    parentId: null,
  },
  {
    id: 'confirm_50yk15dz',
    type: 'confirm',
    label:
      'Tôi đã hiểu rằng nếu nghỉ không lương quá 14 ngày trong tháng, tôi sẽ phải tự đóng hoặc không được đóng BHXH tháng đó theo quy định.',
    name: 'confirm_g1xv96y1',
    placeholder: '',
    note: '',
    required: true,
    readOnly: false,
    order: 7,
    parentId: null,
  },
];
export const formTemplateSeed = [
  {
    fields: annualLeaveFields,
    vieName: 'Đơn Xin Nghỉ Phép Năm',
    engName: 'Annual Leave Request',
    code: 'ANNUAL_LEAVE',
    submitButtonText: 'Gửi yêu cầu',
    maxDays: 12,
    requireAttachment: true,
    autoApprove: false,
    isActive: true,
    isReductible: true,
    ruleWorkflowSequences: [
      {
        id: 'step_1',
        idx: 1,
        label: 'Quản lí trực tiếp',
        name: 'Line Manager',
        specificUserId: '',
        timeExpected: 'Within 24 hours',
      },
    ],
  },
  {
    fields: resignationFields,
    vieName: 'Đơn Nghỉ Việc',
    engName: 'Resignation Request',
    code: 'RESIGNATION_LEAVE',
    submitButtonText: 'Gửi yêu cầu',
    maxDays: 1,
    requireAttachment: true,
    autoApprove: false,
    isActive: true,
    isReductible: true,
    ruleWorkflowSequences: [
      {
        id: 'step_1',
        idx: 1,
        label: 'Quản lí trực tiếp',
        name: 'Line Manager',
        specificUserId: '',
        timeExpected: 'Within 24 hours',
      },
      {
        id: 'step_2',
        idx: 2,
        label: 'Sếp của quản lí trực tiếp',
        name: 'Upper Manager',
        specificUserId: '',
        timeExpected: 'Within 24 hours',
      },
      {
        id: 'step_3',
        idx: 3,
        label: 'Trưởng phòng',
        name: 'Department Head',
        specificUserId: '',
        timeExpected: 'Within 32 hours',
      },
    ],
  },
  {
    fields: unpaidLeaveFields,
    vieName: 'Đơn Nghỉ Không Lương',
    engName: 'Unpaid Leave Request',
    code: 'UNPAID_LEAVE',
    submitButtonText: 'Gửi yêu cầu',
    maxDays: 1,
    requireAttachment: true,
    autoApprove: false,
    isActive: true,
    isReductible: false,
    ruleWorkflowSequences: [
      {
        id: 'step_1',
        idx: 1,
        label: 'Quản lí trực tiếp',
        name: 'Line Manager',
        specificUserId: '',
        timeExpected: 'Within 24 hours',
      },
    ],
  },
];
