// const allFields = [
//   {
//     id: 'text_mdg3fnsg',
//     type: 'text',
//     label: 'Lý do nghỉ',
//     placeholder: '',
//     required: false,
//     readOnly: false,
//     order: 0,
//     parentId: null,
//     layout: {
//       direction: 'col',
//     },
//   },
//   {
//     id: 'number_nt54khps',
//     type: 'number',
//     label: 'New number',
//     placeholder: '',
//     required: false,
//     readOnly: false,
//     order: 1,
//     parentId: null,
//     layout: {
//       direction: 'col',
//     },
//   },
//   {
//     id: 'checkbox_5yw0fp73',
//     type: 'checkbox',
//     label: 'New checkbox',
//     placeholder: '',
//     required: false,
//     readOnly: false,
//     options: [
//       {
//         label: 'Option 1',
//         value: 'opt_1775017323620',
//       },
//       {
//         label: 'Option 2',
//         value: 'opt_1775017323781',
//       },
//       {
//         label: 'Option 3',
//         value: 'opt_1775017323934',
//       },
//     ],
//     order: 2,
//     parentId: null,
//     layout: {
//       direction: 'col',
//     },
//   },
//   {
//     id: 'radio_luqeb6f6',
//     type: 'radio',
//     label: 'New radio',
//     placeholder: '',
//     required: false,
//     readOnly: false,
//     options: [
//       {
//         label: 'Option 1',
//         value: 'opt_1',
//       },
//       {
//         label: 'Option 2',
//         value: 'opt_1775017325356',
//       },
//       {
//         label: 'Option 3',
//         value: 'opt_1775017325509',
//       },
//       {
//         label: 'Option 4',
//         value: 'opt_1775017325656',
//       },
//     ],
//     order: 3,
//     parentId: null,
//     layout: {
//       direction: 'col',
//     },
//   },
//   {
//     id: 'select_zuliexbo',
//     type: 'select',
//     label: 'New select',
//     placeholder: '',
//     required: false,
//     readOnly: false,
//     options: [
//       {
//         label: 'Option 1',
//         value: 'opt_1',
//       },
//       {
//         label: 'Option 2',
//         value: 'opt_1775017327429',
//       },
//       {
//         label: 'Option 3',
//         value: 'opt_1775017327589',
//       },
//     ],
//     order: 4,
//     parentId: null,
//     layout: {
//       direction: 'col',
//     },
//   },
//   {
//     id: 'container_khc8blpv',
//     type: 'container',
//     label: '',
//     placeholder: '',
//     required: false,
//     readOnly: false,
//     order: 1,
//     parentId: null,
//     layout: {
//       direction: 'row',
//     },
//   },
//   {
//     id: 'file_jqqb7pjw',
//     type: 'file',
//     label: 'Đính kèm tệp',
//     placeholder: '',
//     required: false,
//     readOnly: false,
//     order: 2,
//     parentId: null,
//     layout: {
//       direction: 'col',
//     },
//   },
//   {
//     id: 'date_xdvtg807',
//     type: 'date',
//     label: 'Từ ngày:',
//     placeholder: '',
//     required: false,
//     readOnly: false,
//     order: 3,
//     parentId: 'container_khc8blpv',
//     layout: {
//       direction: 'col',
//     },
//   },
//   {
//     id: 'date_fbws9zgs',
//     type: 'date',
//     label: 'Đến ngày:',
//     placeholder: '',
//     required: false,
//     readOnly: false,
//     order: 4,
//     parentId: 'container_khc8blpv',
//     layout: {
//       direction: 'col',
//     },
//   },
// ];
// const minimumFieldTemplate = [
//   {
//     id: 'text_mdg3fnsg',
//     type: 'text',
//     label: 'Lý do nghỉ',
//     placeholder: '',
//     required: false,
//     readOnly: false,
//     order: 0,
//     parentId: null,
//     layout: {
//       direction: 'col',
//     },
//   },
//   {
//     id: 'container_khc8blpv',
//     type: 'container',
//     label: '',
//     placeholder: '',
//     required: false,
//     readOnly: false,
//     order: 1,
//     parentId: null,
//     layout: {
//       direction: 'row',
//     },
//   },
//   {
//     id: 'file_jqqb7pjw',
//     type: 'file',
//     label: 'Đính kèm tệp',
//     placeholder: '',
//     required: false,
//     readOnly: false,
//     order: 2,
//     parentId: null,
//     layout: {
//       direction: 'col',
//     },
//   },
//   {
//     id: 'date_xdvtg807',
//     type: 'date',
//     label: 'Từ ngày:',
//     placeholder: '',
//     required: false,
//     readOnly: false,
//     order: 3,
//     parentId: 'container_khc8blpv',
//     layout: {
//       direction: 'col',
//     },
//   },
//   {
//     id: 'date_fbws9zgs',
//     type: 'date',
//     label: 'Đến ngày:',
//     placeholder: '',
//     required: false,
//     readOnly: false,
//     order: 4,
//     parentId: 'container_khc8blpv',
//     layout: {
//       direction: 'col',
//     },
//   },
// ];
export const formTemplateSeed = [
  {
    code: 'PAID_LEAVE',
    vieName: 'Đơn Xin Nghỉ Phép',
    engName: 'Paid Leave Application Form',
    fields: [
      {
        id: 'container_psutoj9t',
        type: 'container',
        label: 'Container',
        placeholder: '',
        required: false,
        readOnly: false,
        order: 0,
        parentId: null,
        layout: {
          direction: 'row',
        },
      },
      {
        id: 'number_q6m4y8hv',
        type: 'number',
        label: 'Số ngày nghỉ',
        placeholder: 'Nhập số ngày',
        required: false,
        readOnly: false,
        order: 1,
        parentId: null,
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'textarea_dk5a68vh',
        type: 'textarea',
        label: 'Lý do nghỉ:',
        placeholder: 'Nhập lý do nghỉ phép',
        required: true,
        readOnly: false,
        order: 2,
        parentId: null,
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'text_2hvuky4e',
        type: 'text',
        label: 'Bàn giao công việc cho:',
        placeholder: 'Nhập tên',
        required: false,
        readOnly: false,
        order: 3,
        parentId: 'container_kahp14x6',
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'container_kahp14x6',
        type: 'container',
        label: 'Container',
        placeholder: '',
        required: false,
        readOnly: false,
        order: 4,
        parentId: null,
        layout: {
          direction: 'row',
        },
      },
      {
        id: 'textarea_ufjtx6oh',
        type: 'textarea',
        label: 'Nội dung bàn giao',
        placeholder: 'Nhập nội dung bàn giao',
        required: false,
        readOnly: false,
        order: 5,
        parentId: null,
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'file_pn5ry79c',
        type: 'file',
        label: 'Tài liệu đính kèm (Nếu có)',
        placeholder: '',
        required: false,
        readOnly: false,
        order: 6,
        parentId: null,
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'date_r831i9lo',
        type: 'date',
        label: 'Từ ngày:',
        placeholder: '',
        required: true,
        readOnly: false,
        order: 7,
        parentId: 'container_psutoj9t',
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'date_1muyd4k7',
        type: 'date',
        label: 'Đến ngày:',
        placeholder: '',
        required: true,
        readOnly: false,
        order: 8,
        parentId: 'container_psutoj9t',
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'text_abrxlttq',
        type: 'text',
        label: 'Thuộc bộ phận / phòng ban:',
        placeholder: 'Bộ phận / Phòng ban',
        required: false,
        readOnly: false,
        order: 9,
        parentId: 'container_kahp14x6',
        layout: {
          direction: 'col',
        },
      },
    ],
    version: 1,
    isActive: true,
    submitButtonText: 'Gửi yêu cầu',
    autoApprove: false,
    maxDays: 12,
    requireAttachment: false,
    isReductible: false,
  },
  {
    code: 'UNPAID_LEAVE',
    vieName: 'Đơn Xin Nghỉ Không Lương',
    engName: 'Unpaid Leave Application Form',
    fields: [
      {
        id: 'container_g5vmzdlz',
        type: 'container',
        label: 'Container',
        placeholder: '',
        required: false,
        readOnly: false,
        order: 0,
        parentId: null,
        layout: {
          direction: 'row',
        },
      },
      {
        id: 'number_dod1na3s',
        type: 'number',
        label: 'Tổng số ngày nghỉ',
        placeholder: 'Nhập số ngày',
        required: true,
        readOnly: false,
        order: 1,
        parentId: null,
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'textarea_69ou9o9s',
        type: 'textarea',
        label: 'Lý do nghỉ (chi tiết):',
        placeholder: 'Nhập lý do nghỉ',
        required: true,
        readOnly: false,
        order: 2,
        parentId: null,
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'textarea_jzmty6sk',
        type: 'textarea',
        label: 'Cam kết công việc sau khi quay lại:',
        placeholder: '',
        required: true,
        readOnly: false,
        order: 3,
        parentId: null,
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'container_t6viq8mb',
        type: 'container',
        label: 'Container',
        placeholder: '',
        required: false,
        readOnly: false,
        order: 4,
        parentId: null,
        layout: {
          direction: 'row',
        },
      },
      {
        id: 'textarea_8rt293fr',
        type: 'textarea',
        label: 'Nội dung bàn giao:',
        placeholder: 'Nhập nội dung',
        required: false,
        readOnly: false,
        order: 5,
        parentId: null,
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'file_d74b8frc',
        type: 'file',
        label: 'Tài liệu đính kèm (Nếu có)',
        placeholder: '',
        required: false,
        readOnly: false,
        order: 6,
        parentId: null,
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'date_3g05dlzt',
        type: 'date',
        label: 'Từ ngày:',
        placeholder: '',
        required: true,
        readOnly: false,
        order: 7,
        parentId: 'container_g5vmzdlz',
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'date_iff6js6a',
        type: 'date',
        label: 'Đến ngày:',
        placeholder: '',
        required: true,
        readOnly: false,
        order: 8,
        parentId: 'container_g5vmzdlz',
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'text_sb7niikc',
        type: 'text',
        label: 'Người được bàn giao công việc:',
        placeholder: 'Nhập tên',
        required: false,
        readOnly: false,
        order: 9,
        parentId: 'container_t6viq8mb',
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'text_7fpgr77v',
        type: 'text',
        label: 'Thuộc bộ phận / phòng ban:',
        placeholder: 'Bộ phận / Phòng ban',
        required: false,
        readOnly: false,
        order: 10,
        parentId: 'container_t6viq8mb',
        layout: {
          direction: 'col',
        },
      },
    ],
    version: 1,
    isActive: true,
    submitButtonText: 'Gửi yêu cầu',
    autoApprove: false,
    maxDays: 365,
    requireAttachment: false,
    isReductible: false,
  },
  {
    code: 'RESIGNATION',
    vieName: 'Đơn Xin Thôi Việc',
    engName: 'Resignation Form',
    fields: [
      {
        id: 'date_t29n3l3m',
        type: 'date',
        label: 'Ngày nộp đơn:',
        placeholder: '',
        required: true,
        readOnly: false,
        order: 0,
        parentId: 'container_vhfw5pd7',
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'date_jtfnr2ju',
        type: 'date',
        label: 'Thôi việc từ ngày:',
        placeholder: '',
        required: true,
        readOnly: false,
        order: 1,
        parentId: 'container_vhfw5pd7',
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'container_vhfw5pd7',
        type: 'container',
        label: 'New container',
        placeholder: '',
        required: false,
        readOnly: false,
        order: 2,
        parentId: null,
        layout: {
          direction: 'row',
        },
      },
      {
        id: 'textarea_qafle61j',
        type: 'textarea',
        label: 'Lý do thôi việc:',
        placeholder: 'Nhập lý do thôi việc',
        required: true,
        readOnly: false,
        order: 3,
        parentId: null,
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'container_lq947nwd',
        type: 'container',
        label: ' ',
        placeholder: '',
        required: false,
        readOnly: false,
        order: 4,
        parentId: null,
        layout: {
          direction: 'row',
        },
      },
      {
        id: 'text_7cg8xcwj',
        type: 'text',
        label: 'Bàn giao công việc cho:',
        placeholder: 'Nhập tên người được bàn giao',
        required: true,
        readOnly: false,
        order: 5,
        parentId: 'container_lq947nwd',
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'text_9uculv8a',
        type: 'text',
        label: 'Thuộc bộ phận / phòng ban:',
        placeholder: 'Bộ phận / Phòng ban',
        required: true,
        readOnly: false,
        order: 6,
        parentId: 'container_lq947nwd',
        layout: {
          direction: 'col',
        },
      },
      {
        id: 'file_jsqmfy2w',
        type: 'file',
        label: 'Tài liệu đính kèm (Nếu có)',
        placeholder: '',
        required: false,
        readOnly: false,
        order: 7,
        parentId: null,
        layout: {
          direction: 'col',
        },
      },
    ],
    version: 1,
    isActive: true,
    submitButtonText: 'Gửi yêu cầu',
    autoApprove: false,
    maxDays: 0,
    requireAttachment: false,
    isReductible: false,
  },
];
