name: Deploy to Server
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: 157.66.46.64
                  username: root
                  key: ${{ secrets.SSH_PRIVATE_KEY }} # Lưu nội dung file .pem vào GitHub Secret
                  script: |
                      cd /home/leave_request-management
                      git fetch origin main
                      git reset --hard origin/main 
                      npm install --prefix backend
                      npm install --prefix frontend
                      npm run build --prefix backend
                      npm run build --prefix frontend
                      pm2 restart --update-env backend
